<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\books\migrations;

use execut\yii\migration\Inverter;
use execut\yii\migration\Migration;

/**
 * Migration m200708_105338_addBooksTable
 * @package execut\books
 */
class m200708_105338_addBooksTable extends Migration
{
    /**
     * {@inheritDoc}
     */
    public function initInverter(Inverter $i)
    {
        $i->table('example_books')->create([
            'id' => $this->primaryKey()->notNull(),
            'name' => $this->string()->notNull(),
        ]);
    }


    /**
     * {@inheritDoc}
     */
    public function safeUp()
    {
        if ($this->db->getTableSchema('example_books')) {
            return;
        }

        return parent::safeUp(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritDoc}
     */
    public function safeDown()
    {
        if (!$this->db->getTableSchema('example_books')) {
            return;
        }

        return parent::safeUp(); // TODO: Change the autogenerated stub
    }
}

