<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\books\migrations;

use execut\yii\migration\Inverter;
use execut\yii\migration\Migration;

/**
 * Migration m200713_112615_addAuthorsTable
 * @package execut\books
 */
class m200713_112615_addAuthorsTable extends Migration
{
    /**
     * {@inheritDoc}
     */
    public function initInverter(Inverter $i)
    {
        $i->table('example_authors')->create($this->defaultColumns([
            'surname' => $this->string()->notNull(),
            'name' => $this->string()->notNull(),
            'short_description' => $this->text(),
            'biography' => $this->text(),
            'birthday' => $this->date(),
            'popularity' => $this->integer()->unsigned(),
            'email' => $this->string(),
            'image' => $this->binary(),
            'image_211' => $this->binary(),
            'image_name' => $this->string(),
            'image_extension' => $this->string(),
            'image_md5' => $this->string(64),
            'image_mime_type' => $this->string(),
            'main_book_id' => $this->integer()->unsigned()
        ]));
        $i->table('example_authors_vs_books')->create([
                'id' => $this->primaryKey(),
            ])
            ->addForeignColumn('example_authors', true)
            ->addForeignColumn('example_books', true);
    }

    /**
     * {@inheritDoc}
     */
    public function safeUp()
    {
        if ($this->db->getTableSchema('example_authors')) {
            return;
        }

        return parent::safeUp(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritDoc}
     */
    public function safeDown()
    {
        if (!$this->db->getTableSchema('example_authors')) {
            return;
        }

        return parent::safeUp(); // TODO: Change the autogenerated stub
    }
}
